const BIG_POWERS=[
{name:"United States",short:"USA",x:.22,y:.42,tag:"Atlantic superpower"},
{name:"China",short:"CHN",x:.77,y:.42,tag:"Industrial giant"},
{name:"Russia",short:"RUS",x:.68,y:.23,tag:"Northern powerhouse"},
{name:"India",short:"IND",x:.70,y:.55,tag:"Rising economy"},
{name:"United Kingdom",short:"UK",x:.48,y:.28,tag:"Global network"},
{name:"France",short:"FRA",x:.49,y:.37,tag:"Diplomatic power"},
{name:"Germany",short:"GER",x:.53,y:.32,tag:"Economic engine"},
{name:"Japan",short:"JPN",x:.87,y:.39,tag:"Tech leader"},
{name:"Brazil",short:"BRA",x:.34,y:.68,tag:"Resource giant"}];
const state=Object.fromEntries(BIG_POWERS.map(({name})=>[name,{name,taxes:10,happiness:50+Math.floor(Math.random()*21),economy:60+Math.floor(Math.random()*31),infra:20+Math.floor(Math.random()*41),influence:20+Math.floor(Math.random()*41),corruption:5}]));
let player=null,turn=1;
const $=id=>document.getElementById(id),svg=$("worldmap"),log=$("log"),modal=$("decisionModal"),content=$("decisionContent");
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function appendLog(message){const el=document.createElement("div");el.textContent=`Turn ${turn}: ${message}`;log.appendChild(el);log.scrollTop=log.scrollHeight}
function updateLeaderboard(){const list=Object.values(state).sort((a,b)=>b.influence-a.influence);$("leaders").innerHTML=list.map(c=>`<li class="${player&&c.name===player.name?"player":""}"><strong>${c.name}</strong><span>${c.influence} INF</span></li>`).join("")}
function refreshPanel(){$("countryName").textContent=player.name;$("happiness").textContent=player.happiness;$("economy").textContent=player.economy;$("infra").textContent=player.infra;$("influence").textContent=player.influence;$("corruption").textContent=`${player.corruption}%`;$("taxSlider").value=player.taxes;$("taxVal").textContent=`${player.taxes}%`;updateLeaderboard();updateMarkers()}
function chooseCountry(name){player=state[name];$("countryPicker").classList.add("hidden");$("countryPanel").classList.remove("hidden");$("playerBadge").textContent=`PLAYING AS ${name.toUpperCase()}`;refreshPanel();appendLog(`You chose ${name}. Reach 300 influence to win.`)}
function marker(power){const g=document.createElementNS("http://www.w3.org/2000/svg","g"),c=document.createElementNS("http://www.w3.org/2000/svg","circle"),t=document.createElementNS("http://www.w3.org/2000/svg","text"),x=power.x*900,y=power.y*560;g.classList.add("power-marker");g.dataset.country=power.name;c.setAttribute("cx",x);c.setAttribute("cy",y);c.setAttribute("r",13);t.setAttribute("x",x);t.setAttribute("y",y+31);t.setAttribute("text-anchor","middle");t.textContent=power.short;g.append(c,t);g.addEventListener("click",()=>player?appendLog(`${power.name} is at ${state[power.name].influence} influence.`):chooseCountry(power.name));svg.appendChild(g)}
function drawMap(){svg.innerHTML="";["M70 205 Q170 120 315 190 L360 310 Q280 350 190 315 L90 335Z","M390 155 Q465 90 555 155 L535 275 Q475 310 420 255Z","M550 150 Q700 90 835 170 L850 300 Q740 335 610 290 L545 230Z","M260 350 Q340 320 410 385 L385 510 Q310 530 250 440Z","M610 340 Q720 315 830 380 L805 500 Q685 510 615 440Z"].forEach(d=>{const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",d);p.classList.add("continent");svg.appendChild(p)});const title=document.createElementNS("http://www.w3.org/2000/svg","text");title.setAttribute("x",450);title.setAttribute("y",48);title.setAttribute("text-anchor","middle");title.setAttribute("fill","#b3c5d9");title.setAttribute("font-size","16");title.textContent="GLOBAL INFLUENCE MAP";svg.appendChild(title);BIG_POWERS.forEach(marker);updateMarkers()}
function updateMarkers(){document.querySelectorAll(".power-marker").forEach(g=>{const c=state[g.dataset.country],circle=g.querySelector("circle");g.classList.toggle("player",!!player&&g.dataset.country===player.name);circle.style.opacity=.45+Math.min(.55,c.influence/300);circle.setAttribute("r",10+Math.min(7,c.influence/60))})}
const decisions={
 government:{icon:"🏛️",title:"Parliament office",subtitle:"The anime senate is waiting for your vote.",question:"A budget bill is on the desk. What do you tell the senators?",people:["Senator Nova","Senator Kaito","Senator Luna"],options:[["✂️ People-first tax cut","Lower taxes. Happiness +8, economy -4.","happiness",8,"economy",-4],["💼 Fund the national plan","Raise taxes. Economy +12, happiness -7.","economy",12,"happiness",-7],["🤝 Compromise bill","A balanced increase. Influence +6, happiness +2.","influence",6,"happiness",2]]},
 infrastructure:{icon:"🏗️",title:"National project room",subtitle:"Your cabinet has three blueprints ready.",question:"Which project gets the spotlight this turn?",people:["Director Atlas","Engineer Mei","Mayor Sol"],options:[["🚄 Skyline rail network","Fast travel and jobs. Infrastructure +8, economy -18.","infra",8,"economy",-18],["🌱 Green energy grid","Popular and resilient. Happiness +6, infrastructure +4.","happiness",6,"infra",4],["🚢 Global trade port","Connect to the world. Economy +8, influence +7.","economy",8,"influence",7]]},
 media:{icon:"📱",title:"Media studio",subtitle:"Your creative team has prepared three headlines.",question:"What story should dominate the world's feed?",people:["Host Pixel","Editor Yuki","Creator Max"],options:[["🌈 Hopeful future campaign","Build trust. Happiness +5, influence +5.","happiness",5,"influence",5],["🚨 Tax panic headline","Huge clicks, but it hurts morale. Influence +12, happiness -10.","influence",12,"happiness",-10],["🎙️ Diplomatic livestream","Show the world your leadership. Influence +8, economy -6.","influence",8,"economy",-6]]}};
const covertActions=[["🧳 Steal a rival's reserves","High risk: take 25 economy from a target. Failure causes a scandal.","steal"],["🤝 Bribe a foreign government","Pay 18 economy to gain 18 influence and weaken a rival.","bribe"],["🛰️ Leak secret intelligence","Gain 10 influence, but discovery can damage happiness.","leak"]];
function openDecision(type){const d=decisions[type];content.innerHTML=`<div class="decision-title"><span class="big-icon">${d.icon}</span><div><span class="eyebrow">${type.toUpperCase()} DECISION</span><h2>${d.title}</h2><p>${d.subtitle}</p></div></div><div class="senate">${d.people.map((p,i)=>`<div class="senator">${["🧑‍⚖️","👩‍💼","🧑‍💻"][i]}<small>${p}</small></div>`).join("")}</div><div class="decision-question">${d.question}</div><div class="decision-options">${d.options.map((o,i)=>`<button class="decision-option" data-type="${type}" data-index="${i}"><strong>${o[0]}</strong><small>${o[1]}</small></button>`).join("")}</div>`;modal.classList.remove("hidden");document.querySelectorAll(".decision-option").forEach(b=>b.addEventListener("click",()=>applyDecision(type,+b.dataset.index)))}
function applyDecision(type,index){const o=decisions[type].options[index];player[o[2]]=Math.max(0,player[o[2]]+o[3]);player[o[4]]=Math.max(0,player[o[4]]+o[5]);player.happiness=clamp(player.happiness,0,100);player.corruption=clamp(player.corruption,0,100);modal.classList.add("hidden");appendLog(`${decisions[type].title}: ${o[0]} enacted immediately.`);refreshPanel()}
function openCorruption(){const targets=BIG_POWERS.filter(c=>c.name!==player.name).map(c=>`<option value="${c.name}">${c.name}</option>`).join("");content.innerHTML=`<div class="decision-title"><span class="big-icon">🕶️</span><div><span class="eyebrow">COVERT OPERATIONS</span><h2>Black budget room</h2><p>Every operation raises corruption. Failure can trigger a public scandal.</p></div></div><label class="target-label">Target country<select id="covertTarget">${targets}</select></label><div class="decision-options">${covertActions.map((o,i)=>`<button class="decision-option covert-option" data-index="${i}"><strong>${o[0]}</strong><small>${o[1]}</small></button>`).join("")}</div>`;modal.classList.remove("hidden");document.querySelectorAll(".covert-option").forEach(b=>b.addEventListener("click",()=>runCovert(+b.dataset.index,$("covertTarget").value)))}
function runCovert(index,targetName){const target=state[targetName],action=covertActions[index],risk=clamp(0.28+player.corruption/180+(index===0?.12:0),.2,.82),success=Math.random()>risk;player.corruption=clamp(player.corruption+(index===1?14:10),0,100);if(index===0&&player.economy<10){appendLog("Operation cancelled: not enough economy.");return}if(index===1&&player.economy<18){appendLog("Operation cancelled: bribe fund is too small.");return}if(success){if(index===0){player.economy+=25;target.economy=Math.max(0,target.economy-25)}if(index===1){player.economy-=18;player.influence+=18;target.influence=Math.max(0,target.influence-8)}if(index===2)player.influence+=10;appendLog(`🕶️ ${action[0]} succeeded against ${targetName}.`)}else{player.happiness=clamp(player.happiness-8,0,100);player.influence=Math.max(0,player.influence-6);appendLog(`🚨 ${action[0]} failed. ${targetName} exposed the operation.`)}modal.classList.add("hidden");refreshPanel()}
function bind(){document.querySelectorAll(".country-choice").forEach(b=>b.addEventListener("click",()=>chooseCountry(b.dataset.country)));$("taxSlider").addEventListener("input",e=>{player.taxes=+e.target.value;$("taxVal").textContent=`${player.taxes}%`});$("openParliament").addEventListener("click",()=>openDecision("government"));$("openInfrastructure").addEventListener("click",()=>openDecision("infrastructure"));$("openMedia").addEventListener("click",()=>openDecision("media"));$("openCorruption").addEventListener("click",openCorruption);$("closeModal").addEventListener("click",()=>modal.classList.add("hidden"));modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.add("hidden")});$("endTurn").addEventListener("click",()=>{turn++;Object.values(state).forEach(c=>{if(c!==player)c.influence=Math.max(0,c.influence+Math.floor(Math.random()*5)-1);const tax=c.taxes-10;c.economy=Math.max(0,c.economy+Math.round(tax*.5)+Math.round(c.infra*.1));c.happiness=clamp(c.happiness-Math.round(tax*.4)+(Math.random()<.35?1:0),0,100);c.influence+=Math.round(c.infra/10+c.economy/100)});if(player.corruption>35&&Math.random()<.3){player.happiness=clamp(player.happiness-6,0,100);player.influence=Math.max(0,player.influence-5);appendLog("🚨 Corruption scandal! The public demands accountability.")}$("turn").textContent=turn;appendLog("Turn resolved. Every power is making its move.");refreshPanel();if(player.influence>=300)appendLog("You reached global dominance! You win.")})}
function init(){$("countryChoices").innerHTML=BIG_POWERS.map(c=>`<button class="country-choice" data-country="${c.name}"><strong>${c.short} · ${c.name}</strong><small>${c.tag}</small></button>`).join("");bind();drawMap();updateLeaderboard()}
init();
