const BIG_POWERS=[
 {name:"United States",short:"USA",x:.22,y:.42,tag:"Atlantic superpower",strength:"Media",weakness:"Polarization",personality:"Showboat"},
 {name:"China",short:"CHN",x:.77,y:.42,tag:"Industrial giant",strength:"Industry",weakness:"Trust",personality:"Builder"},
 {name:"Russia",short:"RUS",x:.68,y:.23,tag:"Northern powerhouse",strength:"Espionage",weakness:"Economy",personality:"Maverick"},
 {name:"India",short:"IND",x:.70,y:.55,tag:"Rising economy",strength:"People",weakness:"Infrastructure",personality:"Optimist"},
 {name:"United Kingdom",short:"UK",x:.48,y:.28,tag:"Global network",strength:"Diplomacy",weakness:"Industry",personality:"Broker"},
 {name:"France",short:"FRA",x:.49,y:.37,tag:"Diplomatic power",strength:"Culture",weakness:"Taxes",personality:"Idealist"},
 {name:"Germany",short:"GER",x:.53,y:.32,tag:"Economic engine",strength:"Industry",weakness:"Media",personality:"Planner"},
 {name:"Japan",short:"JPN",x:.87,y:.39,tag:"Tech leader",strength:"Technology",weakness:"People",personality:"Inventor"},
 {name:"Brazil",short:"BRA",x:.34,y:.68,tag:"Resource giant",strength:"Culture",weakness:"Corruption",personality:"Charmer"}
];
const traits=Object.fromEntries(BIG_POWERS.map(c=>[c.name,c]));
const state=Object.fromEntries(BIG_POWERS.map(c=>[c.name,{name:c.name,taxes:10,happiness:50+Math.floor(Math.random()*21),economy:60+Math.floor(Math.random()*31),infra:20+Math.floor(Math.random()*41),influence:20+Math.floor(Math.random()*41),corruption:5,reputation:55,popularity:55,bloc:null,allies:[],scandal:0,objective:null}]));
let player=null,turn=1,gameOver=false,currentEvent=null;
const $=id=>document.getElementById(id),svg=$("worldmap"),log=$("log"),modal=$("decisionModal"),content=$("decisionContent");
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const fmt=n=>Math.round(n);
function appendLog(message){const el=document.createElement("div");el.textContent=`Turn ${turn}: ${message}`;log.appendChild(el);log.scrollTop=log.scrollHeight}
function showModal(html){content.innerHTML=html;modal.classList.remove("hidden")}
function closeModal(){modal.classList.add("hidden")}
function victory(c){
 if(c.influence>=300)return["GLOBAL DOMINANCE","You reached 300 influence and became the world's leading power.","🏆"];
 if(c.reputation>=90&&c.allies.length>=3)return["SOFT-POWER VICTORY","Three allies and a trusted reputation made your country indispensable.","🤝"];
 if(c.popularity>=90&&c.happiness>=75)return["PEOPLE'S MANDATE","Citizens gave you an overwhelming popular mandate.","🗳️"];
 if(c.influence>=220&&c.economy>=180&&c.infra>=100)return["ECONOMIC SUPERPOWER","A prosperous, modern nation now sets the global agenda.","💰"];
 if(c.objective&&c.objective.done)return["SECRET MISSION COMPLETE",c.objective.text,"🔐"];
 return null;
}
function checkWinner(){
 if(gameOver)return true;
 const winner=Object.values(state).map(c=>[c,victory(c)]).find(x=>x[1]);
 if(!winner)return false;
 gameOver=true;const [c,v]=winner;
 showModal(`<div class="winner-screen"><div class="result-icon">${v[2]}</div><span class="eyebrow">${v[0]}</span><h2>${c.name} wins!</h2><p>${c.name===player.name?v[1]:`The world has a new leader. ${c.name} achieved victory first.`}</p><strong class="winner-score">${c.influence} influence · ${c.reputation} reputation</strong><button id="restartGame">Play again</button></div>`);
 $("restartGame").addEventListener("click",()=>window.location.reload());appendLog(`🏆 ${c.name} achieved ${v[0]}.`);return true;
}
function updateLeaderboard(){const list=Object.values(state).sort((a,b)=>b.influence-a.influence);$("leaders").innerHTML=list.map(c=>`<li class="${player&&c.name===player.name?"player":""}"><strong>${c.name}</strong><span>${fmt(c.influence)} INF · ${fmt(c.reputation)} REP</span></li>`).join("")}
function refreshPanel(){
 $("countryName").textContent=player.name;$("happiness").textContent=fmt(player.happiness);$("economy").textContent=fmt(player.economy);$("infra").textContent=fmt(player.infra);$("influence").textContent=fmt(player.influence);$("corruption").textContent=`${fmt(player.corruption)}%`;$("taxSlider").value=player.taxes;$("taxVal").textContent=`${player.taxes}%`;
 $("trendTitle").textContent=world.trend.name;$("trendText").textContent=`${world.trend.icon} ${world.trend.text} ${world.trend.bonus}`;$("eventText").textContent=world.event?`📰 ${world.event.title}`:"📰 No breaking news right now.";
 $("blocText").textContent=player.bloc?`${player.bloc} · ${player.allies.length} ally/ies`:"No bloc yet. Alliances protect your reputation.";
 $("publicText").textContent=`Popularity ${fmt(player.popularity)} · Reputation ${fmt(player.reputation)}${player.scandal?" · Investigation pending":""}`;
 $("objectiveText").textContent=player.objective.text;$("globalEventText").textContent=world.global.name;updateLeaderboard();updateMarkers();
}
function chooseCountry(name){if(gameOver)return;player=state[name];player.objective=secretObjectives[Math.floor(Math.random()*secretObjectives.length)]();$("countryPicker").classList.add("hidden");$("countryPanel").classList.remove("hidden");$("playerBadge").textContent=`PLAYING AS ${name.toUpperCase()}`;refreshPanel();appendLog(`You chose ${name}. ${traits[name].strength} is your strength; ${traits[name].weakness} is your weakness.`)}
function marker(power){const g=document.createElementNS("http://www.w3.org/2000/svg","g"),c=document.createElementNS("http://www.w3.org/2000/svg","circle"),t=document.createElementNS("http://www.w3.org/2000/svg","text"),x=power.x*900,y=power.y*560;g.classList.add("power-marker");g.dataset.country=power.name;c.setAttribute("cx",x);c.setAttribute("cy",y);c.setAttribute("r",13);t.setAttribute("x",x);t.setAttribute("y",y+31);t.setAttribute("text-anchor","middle");t.textContent=power.short;g.append(c,t);g.addEventListener("click",()=>player?appendLog(`${power.name}: ${traits[power.name].personality}, ${state[power.name].influence} influence.`):chooseCountry(power.name));svg.appendChild(g)}
function drawMap(){svg.innerHTML="";["M70 205 Q170 120 315 190 L360 310 Q280 350 190 315 L90 335Z","M390 155 Q465 90 555 155 L535 275 Q475 310 420 255Z","M550 150 Q700 90 835 170 L850 300 Q740 335 610 290 L545 230Z","M260 350 Q340 320 410 385 L385 510 Q310 530 250 440Z","M610 340 Q720 315 830 380 L805 500 Q685 510 615 440Z"].forEach(d=>{const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",d);p.classList.add("continent");svg.appendChild(p)});const title=document.createElementNS("http://www.w3.org/2000/svg","text");title.setAttribute("x",450);title.setAttribute("y",48);title.setAttribute("text-anchor","middle");title.setAttribute("fill","#b3c5d9");title.setAttribute("font-size","16");title.textContent="GLOBAL INFLUENCE MAP";svg.appendChild(title);BIG_POWERS.forEach(marker);updateMarkers()}
function updateMarkers(){document.querySelectorAll(".power-marker").forEach(g=>{const c=state[g.dataset.country],circle=g.querySelector("circle");g.classList.toggle("player",!!player&&g.dataset.country===player.name);circle.style.opacity=.45+Math.min(.55,c.influence/300);circle.setAttribute("r",10+Math.min(7,c.influence/60))})}
const world={trend:null,event:null,global:null};
const trends=[{name:"Climate action",icon:"🌱",text:"The world wants greener choices.",bonus:"Green projects gain +4 influence."},{name:"Short-video mania",icon:"📱",text:"Everyone is watching the feed.",bonus:"Social actions gain +5 influence."},{name:"Trade week",icon:"📦",text:"Markets are looking for partners.",bonus:"Trade choices gain +8 economy."},{name:"Cultural exchange",icon:"🎨",text:"Stories cross every border.",bonus:"High reputation gains +3 popularity."}];
const globalEvents=[{name:"World Cup",icon:"⚽",effect:"Host nations gain popularity.",stat:"popularity"},{name:"Future Olympics",icon:"🏟️",effect:"Infrastructure shines on the world stage.",stat:"infra"},{name:"Global music festival",icon:"🎤",effect:"Culture boosts reputation.",stat:"reputation"}];
const secretObjectives=[()=>({text:"Reach 80 reputation without a scandal.",done:false,check:c=>c.reputation>=80&&c.scandal===0}),()=>({text:"Build 100 infrastructure and 90 popularity.",done:false,check:c=>c.infra>=100&&c.popularity>=90}),()=>({text:"Recruit three allies.",done:false,check:c=>c.allies.length>=3}),()=>({text:"Lead the world in economy (150+).",done:false,check:c=>c.economy>=150})];
function newWorldPulse(){world.trend=trends[Math.floor(Math.random()*trends.length)];world.global=globalEvents[(turn-1)%globalEvents.length];if(Math.random()<.55){world.event=breakingEvents[Math.floor(Math.random()*breakingEvents.length)];}else world.event=null}
function change(stat,amount){player[stat]=clamp(player[stat]+amount,0,stat==="economy"||stat==="infra"||stat==="influence"?999:100)}
const decisions={
 government:{icon:"🏛️",title:"Parliament office",subtitle:"Your cabinet needs a clear mandate.",question:"How should the budget serve the public?",people:["Senator Nova","Senator Kaito","Senator Luna"],options:[["✂️ People-first tax cut","Happiness +8, economy -4.","happiness",8,"economy",-4],["💼 Fund the national plan","Economy +12, popularity -7.","economy",12,"popularity",-7],["🤝 Compromise bill","Influence +6, popularity +2.","influence",6,"popularity",2]]},
 infrastructure:{icon:"🏗️",title:"National project room",subtitle:"Three blueprints are ready.",question:"Which project gets the spotlight?",people:["Director Atlas","Engineer Mei","Mayor Sol"],options:[["🚄 Skyline rail network","Infrastructure +8, economy -18.","infra",8,"economy",-18],["🌱 Green energy grid","Happiness +6, infrastructure +4.","happiness",6,"infra",4],["🚢 Global trade port","Economy +8, influence +7.","economy",8,"influence",7]]},
 media:{icon:"📱",title:"Media studio",subtitle:"Your creative team has prepared three headlines.",question:"What story should dominate the feed?",people:["Host Pixel","Editor Yuki","Creator Max"],options:[["🌈 Hopeful future campaign","Reputation +6, influence +5.","reputation",6,"influence",5],["🚨 Tax panic headline","Influence +12, happiness -10.","influence",12,"happiness",-10],["🎙️ Diplomatic livestream","Influence +8, economy -6.","influence",8,"economy",-6]]}
};
function openDecision(type){if(gameOver)return;const d=decisions[type];showModal(`<div class="decision-title"><span class="big-icon">${d.icon}</span><div><span class="eyebrow">${type.toUpperCase()} DECISION</span><h2>${d.title}</h2><p>${d.subtitle}</p></div></div><div class="senate">${d.people.map((p,i)=>`<div class="senator">${["🧑‍⚖️","👩‍💼","🧑‍💻"][i]}<small>${p}</small></div>`).join("")}</div><div class="decision-question">${d.question}</div><div class="decision-options">${d.options.map((o,i)=>`<button class="decision-option" data-index="${i}"><strong>${o[0]}</strong><small>${o[1]}</small></button>`).join("")}</div>`);document.querySelectorAll(".decision-option").forEach(b=>b.addEventListener("click",()=>{const o=d.options[+b.dataset.index];change(o[2],o[3]);change(o[4],o[5]);closeModal();appendLog(`${d.title}: ${o[0]} chosen.`);refreshPanel();checkWinner()}))}
const covertActions=[["🧳 Steal reserves","Take 25 economy from a target.","steal"],["🤝 Bribe government","Pay 18 economy for 18 influence.","bribe"],["🛰️ Leak intelligence","Gain 10 influence, but risk reputation.","leak"]];
function openCorruption(){if(gameOver)return;const targets=BIG_POWERS.filter(c=>c.name!==player.name).map(c=>`<option>${c.name}</option>`).join("");showModal(`<div class="decision-title"><span class="big-icon">🕶️</span><div><span class="eyebrow">COVERT OPERATIONS</span><h2>Black budget room</h2><p>Choose a target, then test your nerve.</p></div></div><label class="target-label">Target country<select id="covertTarget">${targets}</select></label><div class="decision-options">${covertActions.map((o,i)=>`<button class="decision-option covert-option" data-index="${i}"><strong>${o[0]}</strong><small>${o[1]}</small></button>`).join("")}<button class="decision-option" id="openSpy"><strong>🧩 Crack a rival signal</strong><small>Play a quick symbol puzzle for influence.</small></button></div>`);document.querySelectorAll(".covert-option").forEach(b=>b.addEventListener("click",()=>runCovert(+b.dataset.index,$("covertTarget").value)));$("openSpy").addEventListener("click",espionage)}
function runCovert(index,targetName){const target=state[targetName];if(index===0&&player.economy<10||index===1&&player.economy<18){appendLog("Operation cancelled: not enough economy.");return}const risk=clamp(.25+player.corruption/180+(index===0?.12:0),.2,.8),success=Math.random()>risk;player.corruption=clamp(player.corruption+10,0,100);if(success){if(index===0){player.economy+=25;target.economy=Math.max(0,target.economy-25)}if(index===1){player.economy-=18;player.influence+=18;target.influence=Math.max(0,target.influence-8)}if(index===2)player.influence+=10;appendLog(`🕶️ Operation succeeded against ${targetName}.`)}else{player.happiness=clamp(player.happiness-8,0,100);player.reputation=Math.max(0,player.reputation-10);player.scandal=1;appendLog(`🚨 ${targetName} exposed your operation. A scandal is brewing.`)}closeModal();refreshPanel();checkWinner()}
function openSocial(){showModal(`<div class="decision-title"><span class="big-icon">📣</span><div><span class="eyebrow">SOCIAL COMMAND</span><h2>Shape the feed</h2><p>Reputation is slow to build and quick to lose.</p></div></div><div class="decision-options"><button class="decision-option" data-social="campaign"><strong>💬 Listening tour</strong><small>Popularity +10, reputation +4.</small></button><button class="decision-option" data-social="viral"><strong>🔥 Viral challenge</strong><small>Influence +14, popularity -4.</small></button><button class="decision-option" data-social="fact"><strong>✅ Fact-check drive</strong><small>Reputation +10, economy -8.</small></button></div>`);document.querySelectorAll("[data-social]").forEach(b=>b.addEventListener("click",()=>{const a=b.dataset.social;if(a==="campaign"){change("popularity",10);change("reputation",4)}if(a==="viral"){change("influence",14);change("popularity",-4);if(world.trend.name==="Short-video mania")change("influence",5)}if(a==="fact"){change("reputation",10);change("economy",-8)}closeModal();appendLog(`📣 Social action completed: ${a}.`);refreshPanel();checkWinner()}))}
function openDiplomacy(){const targets=BIG_POWERS.filter(c=>c.name!==player.name);showModal(`<div class="decision-title"><span class="big-icon">🤝</span><div><span class="eyebrow">DIPLOMACY</span><h2>Alliance summit</h2><p>Offer aid to recruit a friend or create a new bloc.</p></div></div><label class="target-label">Invite country<select id="allyTarget">${targets.map(c=>`<option>${c.name}</option>`).join("")}</select></label><div class="decision-options"><button class="decision-option" id="inviteAlly"><strong>🤝 Offer partnership</strong><small>Pay 12 economy to gain an ally and +8 reputation.</small></button><button class="decision-option" id="formBloc"><strong>🌐 Form a bloc</strong><small>Found a bloc. Allies gain a small defensive bonus.</small></button></div>`);$("inviteAlly").addEventListener("click",()=>{const n=$("allyTarget").value;if(player.economy<12){appendLog("You need 12 economy for a partnership.");return}player.economy-=12;if(!player.allies.includes(n)){player.allies.push(n);state[n].allies.push(player.name);player.reputation+=8;appendLog(`🤝 ${n} joined your alliance.`)}closeModal();refreshPanel();checkWinner()});$("formBloc").addEventListener("click",()=>{player.bloc=player.bloc||`${player.name.split(" ")[0]} Accord`;player.reputation+=3;appendLog(`🌐 The ${player.bloc} was announced.`);closeModal();refreshPanel()})}
function openInvestigation(){if(!player.scandal){appendLog("No active scandal to investigate.");return}showModal(`<div class="decision-title"><span class="big-icon">🔎</span><div><span class="eyebrow">PUBLIC INQUIRY</span><h2>Investigate the scandal</h2><p>Choose transparency or a cover-up.</p></div></div><div class="decision-options"><button class="decision-option" id="truth"><strong>🧾 Publish the findings</strong><small>Reputation +12, popularity +4, economy -10.</small></button><button class="decision-option" id="cover"><strong>🕳️ Bury the report</strong><small>Influence +8, corruption +12, reputation -8.</small></button></div>`);$("truth").addEventListener("click",()=>resolveInvestigation(true));$("cover").addEventListener("click",()=>resolveInvestigation(false))}
function resolveInvestigation(open){player.scandal=0;if(open){change("reputation",12);change("popularity",4);change("economy",-10);appendLog("🔎 Transparency restored public trust.")}else{change("influence",8);change("corruption",12);change("reputation",-8);appendLog("🕳️ The cover-up worked—for now.")}closeModal();refreshPanel()}
const breakingEvents=[{title:"Breaking: Water shortage",text:"A dry season is testing every capital.",options:[["🚰 Share supplies","Reputation +8, economy -10.","reputation",8,"economy",-10],["💼 Protect reserves","Economy +12, popularity -8.","economy",12,"popularity",-8]]},{title:"Breaking: Platform leak",text:"A major social platform has lost public trust.",options:[["🛡️ Regulate fairly","Reputation +10, influence +4.","reputation",10,"influence",4],["📢 Ride the outrage","Influence +12, reputation -6.","influence",12,"reputation",-6]]},{title:"Breaking: Peace talks",text:"Two rivals are asking you to mediate.",options:[["🕊️ Host the talks","Reputation +12, influence +7.","reputation",12,"influence",7],["🧱 Pick a side","Influence +14, reputation -4.","influence",14,"reputation",-4]]}];
function openBreakingEvent(){if(!world.event)return;const e=world.event;showModal(`<div class="decision-title"><span class="big-icon">📰</span><div><span class="eyebrow">BREAKING NEWS</span><h2>${e.title}</h2><p>${e.text}</p></div></div><div class="decision-options">${e.options.map((o,i)=>`<button class="decision-option" data-event="${i}"><strong>${o[0]}</strong><small>${o[1]}</small></button>`).join("")}</div>`);document.querySelectorAll("[data-event]").forEach(b=>b.addEventListener("click",()=>{const o=e.options[+b.dataset.event];change(o[2],o[3]);change(o[4],o[5]);world.event=null;appendLog(`📰 Breaking news choice: ${o[0]}.`);closeModal();refreshPanel();checkWinner()}))}
function espionage(){const code=["▲","●","■"][Math.floor(Math.random()*3)],opts=["▲","●","■"].sort(()=>Math.random()-.5);showModal(`<div class="decision-title"><span class="big-icon">🛰️</span><div><span class="eyebrow">ESPIONAGE MINI-GAME</span><h2>Crack the rival signal</h2><p>Choose the symbol that matches the intercepted code: <strong>${code}</strong></p></div></div><div class="decision-options">${opts.map(o=>`<button class="decision-option signal" data-signal="${o}"><strong>${o}</strong><small>Decrypt this signal</small></button>`).join("")}</div>`);document.querySelectorAll(".signal").forEach(b=>b.addEventListener("click",()=>{if(b.dataset.signal===code){change("influence",16);change("reputation",3);appendLog("🛰️ Signal cracked! Influence +16.")}else{change("reputation",-8);player.scandal=1;appendLog("🛰️ Wrong signal. The rival detected you.")}closeModal();refreshPanel();checkWinner()}))}
function aiTurn(){Object.values(state).filter(c=>c!==player).forEach(c=>{const t=traits[c.name],roll=Math.random();if(roll<.3){c.influence+=t.strength==="Media"?8:4;c.reputation+=2}else if(roll<.6){c.economy+=10;c.infra+=3}else{c.happiness=clamp(c.happiness+4,0,100);c.popularity=clamp(c.popularity+3,0,100)}if(c.personality==="Maverick"&&Math.random()<.25)c.corruption+=5});}
function endTurn(){if(gameOver)return;turn++;const tax=player.taxes-10;Object.values(state).forEach(c=>{const t=c.taxes-10;c.economy=Math.max(0,c.economy+Math.round(t*.5)+Math.round(c.infra*.1));c.happiness=clamp(c.happiness-Math.round(t*.35)+(Math.random()<.35?1:0),0,100);c.influence+=Math.round(c.infra/10+c.economy/100)});aiTurn();change("economy",Math.round(tax*.5)+Math.round(player.infra*.1));change("happiness",-Math.round(tax*.35));if(traits[player.name].strength==="Industry")change("economy",3);if(traits[player.name].strength==="People")change("popularity",3);if(traits[player.name].weakness==="Economy")change("economy",-2);if(traits[player.name].weakness==="People")change("happiness",-2);if(turn%4===0){if(player.popularity>=50){change("influence",8);appendLog("🗳️ Election night: your popular mandate earns +8 influence.")}else{change("happiness",-6);appendLog("🗳️ Election night: low popularity causes a confidence crisis.")}}if(player.corruption>35&&Math.random()<.3){player.happiness=clamp(player.happiness-6,0,100);player.influence=Math.max(0,player.influence-5);player.scandal=1;appendLog("🚨 Corruption scandal! Investigate it before your reputation collapses.")}if(world.global.stat==="infra")change("influence",Math.floor(player.infra/25));if(world.global.stat==="popularity")change("popularity",2);if(world.global.stat==="reputation")change("reputation",2);if(player.objective&&!player.objective.done&&player.objective.check(player)){player.objective.done=true;appendLog("🔐 Secret objective complete! It can now unlock a victory.")}newWorldPulse();$("turn").textContent=turn;appendLog(`Turn resolved. Rival personalities made their moves. ${world.trend.icon} ${world.trend.name} is trending.`);refreshPanel();checkWinner()}
function bind(){$("countryChoices").innerHTML=BIG_POWERS.map(c=>`<button class="country-choice" data-country="${c.name}"><strong>${c.short} · ${c.name}</strong><small>${c.tag} · Strength: ${c.strength}</small></button>`).join("");document.querySelectorAll(".country-choice").forEach(b=>b.addEventListener("click",()=>chooseCountry(b.dataset.country)));$("taxSlider").addEventListener("input",e=>{player.taxes=+e.target.value;$("taxVal").textContent=`${player.taxes}%`});$("openParliament").addEventListener("click",()=>openDecision("government"));$("openInfrastructure").addEventListener("click",()=>openDecision("infrastructure"));$("openMedia").addEventListener("click",()=>openDecision("media"));$("openCorruption").addEventListener("click",openCorruption);$("openSocial").addEventListener("click",openSocial);$("openDiplomacy").addEventListener("click",openDiplomacy);$("openInvestigation").addEventListener("click",openInvestigation);$("eventText").addEventListener("click",openBreakingEvent);$("eventText").classList.add("clickable");$("closeModal").addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal&&!gameOver)closeModal()});$("endTurn").addEventListener("click",endTurn)}
function init(){newWorldPulse();bind();drawMap();updateLeaderboard();$("eventText").title="Click to respond to breaking news."}
init();
